ALTER TABLE users ADD COLUMN IF NOT EXISTS sport_grade TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS trad_grade TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS belay_top_rope BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS belay_lead BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS belay_multi_pitch BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE users ALTER COLUMN sport_grade SET DEFAULT '';
ALTER TABLE users ALTER COLUMN trad_grade SET DEFAULT '';

UPDATE users SET sport_grade = '' WHERE sport_grade IN ('5.10a');
UPDATE users SET trad_grade = '' WHERE trad_grade IN ('5.9');
